# Generated by Django 4.2.16 on 2024-09-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('conference', 'Конференц-зал'), ('office', 'Офіс'), ('meeting', 'Зала для зустрічей')], default='meeting', max_length=50),
        ),
    ]
